// <auto-generated />
namespace BlogSystem.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class createBlog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createBlog));
        
        string IMigrationMetadata.Id
        {
            get { return "201911181046056_createBlog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
